site_name: "blitzly ⚡️"
site_dir: public
docs_dir: ./docs
repo_url: https://github.com/invia-flights/blitzly
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: True
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  language: en
  favicon: assets/images/icon.png
  logo: assets/images/icon.png
  features:
    - navigation.tracking
    - navigation.top
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: false

nav:
  - Plots:
      - Histogram: histogram.md
