name: Auto approve

on:
  pull_request_target:
    branches: [main]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      github.actor == 'github-actions[bot]'
      && github.event.label.name == 'autorelease: pending'
      && startsWith(github.event.head_commit.message, 'chore(main): release')
    steps:
      - uses: hmarr/auto-approve-action@v3
