name: automerge
on:
  pull_request:
    branches: [main]
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    branches: [main]
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'github-actions'
      && github.event.label.name == 'autorelease: pending'
      && startsWith(github.event.head_commit.message, 'chore(main): release')
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
