name: BuildDocs

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install poetry==1.3.1
      - run: poetry install --with docs
      - run: poetry run mkdocs gh-deploy --force --clean --verbose
