name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies and project
        run: |
          python -m pip install poetry==1.3.1
          poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest --cov blitzly --cov-report term-missing --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
