name: DeployPackage

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(main)') }}
    runs-on: ubuntu-latest
    environment: deploy-package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install poetry==1.3.1
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry publish --build
