name: Release
on:
  push:
    branches:
      - release_action
jobs:
  changelog:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "./.github/changelog_config.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: blitzly
          prerelease: true
          default-branch: release_action

  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: deploy-package
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.10"
  #     - run: pip install poetry==1.3.1
  #     - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
  #     - run: poetry publish --build
