name: ResetDevelop

on:
  push:
    branches:
      - main

jobs:
  reset-develop:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(main)') }}
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout main
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Git checkout develop
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Git reset develop
      run: |
        git --version
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status
        git branch -a
        git log -n 5 --oneline
        git reset --hard remotes/origin/main
        git push --force-with-lease
